# -*- coding: utf-8 -*-
"""Mall Data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsvV5LoBul2RUdCR7cqUIhpei0Uc8y1p
"""

import pandas as pd

df=pd.read_csv("/content/Mall_Customers.csv")
df

# Show True/False for missing values
print(df.isnull())

#Remove duplicate rows
print(df.drop_duplicates())

# Strip extra spaces and convert to lowercase
df['Gender'] = df['Gender'].str.strip().str.lower()

gender_map = {
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female'}

df['Gender'] = df['Gender'].map(gender_map)
df

# Rename column headers to be clean and uniform
df.columns = df.columns.str.strip().str.lower()
print(df.columns)